a = input('Insira algo: ')
print('O tipo primitivo deste valor é ',type (a))
print('Esse valor só tem espaços? ',a.isspace ())
print('É um número? ',a.isnumeric ())
print('É alfabético? ',a.isalpha ())
print('É alfanumérico? ',a.isalnum ())
print('Está em maiúsculas? ',a.isupper())
print('Está em minúsculas? ',a.islower ())
print('Está capitalizada? ',a.istitle ())